### ISSUE TITLE
MACS2 ValueError bug

### ISSUE THREAD

**Issue by fxquah** [fxquah/chipseq-snakemake#1]
MACS2 version 2.2.5 , installed with conda gave this error:

```
INFO  @ Thu, 28 Nov 2019 23:45:24: #3 Suggest a cutoff... 
/mnt/home3/fxq20/anaconda3/lib/python3.7/site-packages/MACS2/callpeak_cmd.py:256: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  peakdetect.call_peaks()
Traceback (most recent call last):
  File "/mnt/home3/fxq20/anaconda3/bin/macs2", line 652, in <module>
    main()
  File "/mnt/home3/fxq20/anaconda3/bin/macs2", line 51, in main
    run( args )
  File "/mnt/home3/fxq20/anaconda3/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 256, in run
    peakdetect.call_peaks()
  File "MACS2/PeakDetect.pyx", line 107, in MACS2.PeakDetect.PeakDetect.call_peaks
  File "MACS2/PeakDetect.pyx", line 273, in MACS2.PeakDetect.PeakDetect.__call_peaks_w_control
  File "MACS2/IO/CallPeakUnit.pyx", line 860, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks
  File "MACS2/IO/CallPeakUnit.pyx", line 882, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks
  File "MACS2/IO/CallPeakUnit.pyx", line 856, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pre_computes
ValueError: Unknown format code 'd' for object of type 'float'
```

**Comment by fxquah** [comment]
It could be related to this bug: https://github.com/taoliu/MACS/issues/108

**Comment by fxquah** [comment]
When I run that same code on an older version of MACS2 2.1.2 based on Python2, I do not get this error. It seems to be an issue with incompatibility between Python version, because the later versions of MACS2 (like 2.2.5) are based on Python3.

Should open an issue on MACS2 github.

**Comment by fxquah** [comment]
Fixing this bug is beyond my capability. To work around this, I use the `conda` directive to run MACS2 in Python2 environment, as defined in `envs/py2.yml`.
